version: "3.4"

services:
  api-gateway:
    image: api-gateway:local
    # pull_policy: always
    container_name: api-gateway
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - 8080:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
