# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: "3.4"

services:
  mealinformation-api:
    image: mealinformation
    container_name: meal-information
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
